#!/bin/sh

$CFG_PATH = $1


if ["$CFG_PATH" -eq "" ]
then
    echo "switch2fj228 config_dir_path"
    echo "  - changes all necessary in th eproject by the config files from the passed config directory"
    echo
    echo "parameter config_dir_path missing"
    echo
else
    mv ./docs/config.xml ./docs/config.xml.bck
    cp $CFG_PATH/config.xml ./docs/config.xml

    mv ./docs/publish.sh ./docs/publish.sh.bck
    cp $CFG_PATH/publish.sh ./docs/publish.sh

    mv ./wwwroot/start.html ./wwwroot/start.html.bck
    cp $CFG_PATH/start.html ./wwwroot/start.html

    mv ./wwwroot/start2.html ./wwwroot/start2.html.bck
    cp $CFG_PATH/start2.html ./wwwroot/start2.html

    mv ./wwwroot/server/common.php ./wwwroot/server/common.php.bck
    cp $CFG_PATH/server/common.php ./wwwroot/server/common.php
fi