#!/bin/sh

CFG_PATH="$1"

if [ ! -n "$CFG_PATH" ]
then
    echo "switch2config config_dir_path"
    echo "  - changes all necessary in th eproject by the config files from the passed config directory"
    echo
    echo "ERROR: Parameter config_dir_path is missing."
    echo
else
    echo "The config directory: $CFG_PATH"
    
    mv ./docs/config.xml ./docs/config.xml.bck
    cp $CFG_PATH/config.xml ./docs/config.xml

    mv ./docs/publish.sh ./docs/publish.sh.bck
    cp $CFG_PATH/publish.sh ./docs/publish.sh

    mv ./wwwroot/start.html ./wwwroot/start.html.bck
    cp $CFG_PATH/start.html ./wwwroot/start.html

    mv ./wwwroot/start2.html ./wwwroot/start2.html.bck
    cp $CFG_PATH/start2.html ./wwwroot/start2.html

    mv ./wwwroot/server/common.php ./wwwroot/server/common.php.bck
    cp $CFG_PATH/common.php ./wwwroot/server/common.php
fi