#!/bin/sh

CFG_PATH="$1"

if [ ! -n "$CFG_PATH" ]
then
    echo "switch2config config_dir_path"
    echo "  - changes all necessary in th eproject by the config files from the passed config directory"
    echo
    echo "ERROR: Parameter config_dir_path is missing."
    echo
else
    echo "The config directory: $CFG_PATH"
    
    mv ./server/app_controller.php ./server/app_controller.php.bck
    cp $CFG_PATH/app_controller.php ./server/app_controller.php

    mv ./server/config/database.php ./server/config/database.php.bck
    cp $CFG_PATH/database.php ./server/config/database.php

    mv ./server/webroot/.htaccess ./server/webroot/.htaccess.bck
    cp $CFG_PATH/.htaccess ./server/webroot/.htaccess

    mv ./server/webroot/index.php ./server/webroot/index.php.bck
    cp $CFG_PATH/index.php ./server/webroot/index.php

    mv ./client/form/worker/externalSubmit.html ./client/form/worker/externalSubmit.html.bck
    cp $CFG_PATH/externalSubmit.html ./client/form/worker/externalSubmit.html

    mv ./client/static/js/ui1/Config.js ./client/static/js/ui1/Config.js.bck
    cp $CFG_PATH/Config.js ./client/static/js/ui1/Config.js


    # set the correct rights
    chmod -R 777 ./server/tmp/
    chmod -R 755 ./server/webroot/


fi
